### ISSUE TITLE
version 1.1.0 is not working in grid3 client

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#42]
```bash
yarn ts-node --project ./tsconfig-node.json scripts/single_vm.ts
yarn run v1.22.18
$ /sandbox/code/github/threefoldtech/grid3_client_ts/node_modules/.bin/ts-node --project ./tsconfig-node.json scripts/single_vm.ts
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-03-21 14:28:26        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-03-21 14:28:26        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Key with address: 5EFkv5SZqRRBEL9sxXd7RmzSQk7JCpxgWh6TiJjEq5X77Sb9 is loaded.
Executing method: getTwinIdByAccountId with args: 5EFkv5SZqRRBEL9sxXd7RmzSQk7JCpxgWh6TiJjEq5X77Sb9
Validation succeed
Executing method: getBalanceOf with args: 5EFkv5SZqRRBEL9sxXd7RmzSQk7JCpxgWh6TiJjEq5X77Sb9
Error: Error getting node 11: TypeError: Cannot read properties of undefined (reading 'mru')
    at /sandbox/code/github/threefoldtech/grid3_client_ts/src/primitives/nodes.ts:219:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Nodes.nodeHasResources (/sandbox/code/github/threefoldtech/grid3_client_ts/src/primitives/nodes.ts:312:27)
    at async VMHL.create (/sandbox/code/github/threefoldtech/grid3_client_ts/src/high_level/machine.ts:61:15)
    at async MachinesModule._createDeployment (/sandbox/code/github/threefoldtech/grid3_client_ts/src/modules/machines.ts:44:46)
    at async MachinesModule.deploy (/sandbox/code/github/threefoldtech/grid3_client_ts/src/modules/machines.ts:84:54)
    at async MachinesModule.descriptor.value (/sandbox/code/github/threefoldtech/grid3_client_ts/src/modules/utils.ts:14:16)
    at async MachinesModule.descriptor.value (/sandbox/code/github/threefoldtech/grid3_client_ts/src/helpers/validator.ts:23:16)
    at async main (/sandbox/code/github/threefoldtech/grid3_client_ts/scripts/single_vm.ts:45:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mohamedamer453** [comment]
Verified on devnet.

Latest Version is now working with grid3 client without any issues.

```bash
mohamed@mohamed-Inspiron-3576:~/Desktop/Threefold Repos/FarmerBot/tsclient/grid3_client_ts$ npx ts-node --project tsconfig-node.json scripts/single_vm.ts 
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-03-21 17:17:43        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-03-21 17:17:43        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Key with address: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ is loaded.
2023-03-21 17:17:48        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
2023-03-21 17:18:02        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
phase: {"applyExtrinsic":1}, section: balances, method: Withdraw
phase: {"applyExtrinsic":1}, section: tfgridModule, method: TwinUpdated
phase: {"applyExtrinsic":1}, section: balances, method: Deposit
phase: {"applyExtrinsic":1}, section: transactionPayment, method: TransactionFeePaid
phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicSuccess
Executing method: getTwinIdByAccountId with args: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ
Validation succeed
Executing method: getBalanceOf with args: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ
Adding node 11 to network wedtest5
Node 11 reserved ports: [443,2298,3736,6895,5225,5938,4938,3073,4828,9943,80,4515,6328,9945,3318,3842,2634,3042,3090,2163,2641,3670,6811,3903,7461,2210,9944,8082,3387,6448,2404,7677,3000,7079,4952]
Generating peers for network wedtest5
Creating a vm on node: 11, network: wedtest5 with private ip: 10.249.2.2
Merging workloads
Validation succeed
Updating network workload with name: wedtest5
Deploying on node_id: 11
Lock acquired
2023-03-21 17:18:12        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
2023-03-21 17:18:24        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
phase: {"applyExtrinsic":14}, section: balances, method: Withdraw
phase: {"applyExtrinsic":14}, section: smartContractModule, method: ContractCreated
phase: {"applyExtrinsic":14}, section: balances, method: Deposit
phase: {"applyExtrinsic":14}, section: transactionPayment, method: TransactionFeePaid
phase: {"applyExtrinsic":14}, section: system, method: ExtrinsicSuccess
Lock released
Contract with id: 20284 has been created
A deployment has been created on node_id: 11 with contract_id: 20284
Waiting for deployment with contract_id: 20284 to be ready
Executing method: getContractByID with args: 20284
Executing method: getContractByID with args: 20284
Executing method: getContractByID with args: 20284
{
  contracts: {
    created: [
      {
        version: 4,
        state: { created: null },
        contractId: 20284,
        twinId: 60,
        contractType: {
          nodeContract: {
            nodeId: 11,
            deploymentHash: '0x6236333032633464636132383336613634386334363137653539376464653633',
            deploymentData: '0x7b2774657374564d73273a20747275657d',
            publicIps: 0,
            publicIpsList: []
          }
        },
        solutionProviderId: null
      }
    ],
    updated: [],
    deleted: []
  },
  wireguard_config: ''
}
Executing method: getContractByID with args: 20284
[
  {
    version: 0,
    contractId: 20284,
    nodeId: 11,
    name: 'testvm5',
    created: 1679411910,
    status: 'ok',
    message: '',
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist',
    publicIP: null,
    planetary: '302:9e63:7d43:b742:f061:d61e:3b57:92e2',
    interfaces: [ { network: 'wedtest5', ip: '10.249.2.2' } ],
    capacity: { cpu: 1, memory: 2048 },
    mounts: [
      {
        name: 'wedDisk6',
        mountPoint: '/testdisk',
        size: 8589934592,
        state: 'ok',
        message: ''
      }
    ],
    env: {
      SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCL/v8SGfebsOuaBSXqF/fIFRQ7Q8ycbjRVA12Adn7zAcaDj0drjjzIoodNfiFVndmotb2wPu8nuhnpWltRVnAwMGU2e0Xo4Np8E9Dh5Q+AbAHedp15uUt76fOuOiRdpNUBvwZ56b1WtoW7D3qmpG8AMucI5CqAmJlbqvUpXiQgWJjcgEtDePyL3NWZe35WvLQy7dSXUX2tObyehkMgo+hRvhS9EQsM3cIoJn2dzHEiutsWSgLAphLkKD7kmmtY1uBs5We87i5XraLRM/Mzje7RRL1+8XHr0X+7tJqvL386qxZ284gbKDxNpuMSy0lFxj1ihvyM6aLn9T5xw+TxPA6CwzXu43eRKZ0atQQ08pdpEgPjg67kosfNFN15JBzpWQ4+WuHLv1uy8C24K/Ib3u8Rthm40E18kX73GEFH+b/yV5N0onsNNYeRGiKZBppYyY6QdnTSaQ3GO8YnA3UyrxY9P/Z4Ozjt7xN/vqE87aiz92S3AdP6uuy1Gzw5xyLxT78= mohamed@mohamed-Inspiron-3576'
    },
    entrypoint: '/sbin/zinit init',
    metadata: "{'testVMs': true}",
    description: 'test deploying VMs via ts grid3 client',
    rootfs_size: 0,
    corex: false
  }
]
```
