### ISSUE TITLE
websocket closes at ping pong 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/rmb-sdk-ts#45]
A mnemonic of a twin with no pk was entered. When the node.ts script is executed the following error arises. The error source is ping pong

```
$ ts-node --project ./tsconfig-node.json ./examples/direct/node.ts
2023-03-26 14:00:12        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-03-26 14:00:12        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
2023-03-26 14:00:18        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
2023-03-26 14:00:31        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
phase: {"applyExtrinsic":1}, section: balances, method: Withdraw
phase: {"applyExtrinsic":1}, section: tfgridModule, method: TwinUpdated
phase: {"applyExtrinsic":1}, section: balances, method: Deposit
phase: {"applyExtrinsic":1}, section: transactionPayment, method: TransactionFeePaid
phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicSuccess
/home/amira/cs/rmb-sdk-ts/node_modules/ws/lib/websocket.js:285
      abortHandshake(this, this._req, msg);
      ^
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/amira/cs/rmb-sdk-ts/node_modules/ws/lib/websocket.js:285:7)
    at Client.createConnection (/home/amira/cs/rmb-sdk-ts/lib/client.ts:69:22)
    at Client.ping (/home/amira/cs/rmb-sdk-ts/lib/client.ts:220:26)
    at async Client.__pingPong (/home/amira/cs/rmb-sdk-ts/lib/client.ts:55:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amiraabouhadid** [comment]
issue source was found to originate from dashboard https://github.com/threefoldtech/rmb-sdk-ts/issues/47
